# Generated by Django 5.0.8 on 2024-08-21 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Biova', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogs',
            new_name='Blog',
        ),
        migrations.RenameModel(
            old_name='Features',
            new_name='Feature',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
