# Generated by Django 5.0.8 on 2024-08-21 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Biova', '0002_rename_blogs_blog_rename_features_feature_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
    ]
