# Generated by Django 5.0.8 on 2024-08-21 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Biova', '0004_rename_category_categorie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
