# Generated by Django 5.0.8 on 2024-09-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biova', '0008_blog_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.TextField()),
            ],
        ),
    ]
