# Generated by Django 5.0.8 on 2024-09-17 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Biova', '0009_newsletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsLetter',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='userName',
        ),
    ]
